### ISSUE TITLE
Source Build Bot not working

### ISSUE THREAD

**Issue by flerach** [social-manager-tools/social-manager-tools#27]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.5.1
- **Operating System:** Windows 10 1803

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

C:\Users\filip\Downloads\social-manager-tools-0.5.1>npm run start

> social-manager-tools@0.5.1 start C:\Users\filip\Downloads\social-manager-tools-0.5.1
> electron .

[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
[INFO] login: loading...
[INFO] login: open_loginpage
[INFO] utils: Bot is updated! :D
[INFO] login: set_username
[INFO] login: set_password
[INFO] login: submit
(node:5840) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Node is either not visible or not an HTMLElement
(node:5840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Download Source
2. start cmd
3. cd social-manager-tools-0.5.1
4. npm install
5. npm run start
6. start insta or twitter bot

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
I work at this problem on windows, solution: 
downgrade puppeteer: **`npm install puppeteer@1.4.0`**

**Comment by ptkdev** [comment]
Fixed in **`0.5.2`**

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
