### ISSUE TITLE
Source Build Instagram SQLITE missing

### ISSUE THREAD

**Issue by flerach** [social-manager-tools/social-manager-tools#30]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.5.2
- **Operating System:** Windows 10 1803

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\Users\filip\Downloads\social-manager-tools-0.5.2>npm run start

> social-manager-tools@0.5.2 start C:\Users\filip\Downloads\social-manager-tools-0.5.2
> electron .


(node:9188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\sqlite3\lib\binding\electron-v2.0-win32-x64\node_sqlite3.node'
(node:9188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. source download
2. start cmd
3. cd social-manager-tools-0.5.2
4. npm install
5. npm run start
6. start instagram

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
This is sqllite3 [bug with electron](https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron):
1. `npm install electron electron-builder -g`
2. `npm install`
3. `npm run start` (received error)
4. **`npm run rebuild`**
5. `npm run start`

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>

**Comment by ptkdev** [comment]
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

@flerach  You need install python, sorry for this problem but i develop on Linux.

**Comment by flerach** [comment]
C:\Users\filip\Downloads\social-manager-tools-0.5.2>npm run rebuild

> social-manager-tools@0.5.2 rebuild C:\Users\filip\Downloads\social-manager-tools-0.5.2
> electron-rebuild -w sqlite3 -p

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\filip\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\filip\\Downloads\\social-manager-tools-0.5.2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\\filip\\Downloads\\social-manager-tools-0.5.2\\node_modules\\sqlite3\\lib\\binding\\electron-v2.0-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.2/{toolset}/" "--package_name=electron-v2.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\sqlite3
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\filip\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\filip\\Downloads\\social-manager-tools-0.5.2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=node_sqlite3" "--module_path=C:\\Users\\filip\\Downloads\\social-manager-tools-0.5.2\\node_modules\\sqlite3\\lib\\binding\\electron-v2.0-win32-x64" "--host=https://mapbox-node-binary.s3.amazonaws.com" "--remote_path=./{name}/v4.0.2/{toolset}/" "--package_name=electron-v2.0-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\sqlite3
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\Users\filip\Downloads\social-manager-tools-0.5.2\node_modules\rxjs\Subscriber.js:191:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! social-manager-tools@0.5.2 rebuild: `electron-rebuild -w sqlite3 -p`
npm ERR! Exit status 4294967295

**Comment by ptkdev** [comment]
Try run without rebuild: npm run start 
IMHO if you have Python now work.

**Comment by flerach** [comment]
python is installed but stil sqllite error when starting and rebuilding is not working :P

**Comment by ptkdev** [comment]
P.s. why you don't use official Windows build in release tab?
https://github.com/social-manager-tools/social-manager-tools/releases/download/0.5.2/Social.Manager.Tools-0.5.2.zip

**Comment by flerach** [comment]
because i need a build with fastlike_max 15 mins and fastlike_min 1 min but since 0.5.1 build from source is not working...

**Comment by ptkdev** [comment]
Aaaah, sorry but `fastlike_max` and `fastlike_min` is deprecated. 

Now all mode work with `bot_likeday_min`/`bot_likeday_max`. Is more accurate value.

**Comment by ptkdev** [comment]
See instagram-bot [Changelog v0.9.0](url
https://github.com/social-manager-tools/instagram-bot.js/blob/master/CHANGELOG.md)

**Comment by ptkdev** [comment]
@flerach try install `npm install sqlite3 -g` globally, imho work.

**Comment by ptkdev** [comment]
Work wih **`v0.5.3`** release

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
