### ISSUE TITLE
Wrong instructions on where to find Post you've liked, on InstagramBot start

### ISSUE THREAD

**Issue by federico9292** [social-manager-tools/social-manager-tools#41]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.6.0
- **Operating System:** Windows 10

### Expected Behavior

Correct instructions on where to find "post you've liked"  : open Instagram app, tap the user icon on bottom-right, three-line icon in top-left position, Settings, post you've liked.

### Actual Behavior

Wrong instructions : "tap 3 dots on top-right corner, tap on Post you've liked"

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. open social Manager Tools
2. select InstragramBot
3. start 

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/17730674/46942669-1d382980-d06e-11e8-9930-1494c7cd1030.png)

**Comment by ptkdev** [comment]
<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
