### ISSUE TITLE
Interval Time

### ISSUE THREAD

**Issue by agus-ringgo** [social-manager-tools/social-manager-tools#47]
( finish fast comment, bot sleep 53 - 64 minutes. ) 
Hir sir, this interval time is too long sir, please make an option for configure this in menu.

Thank you very much sir.

**Comment by agus-ringgo** [comment]
I change to 500 thi sresult sir,. 
finish fast comment, bot sleep 32 - 36 minutes

**Comment by ptkdev** [comment]
This is correct. Bot write 12 comment, sleep ~33min and after 24h is 500 comment.

Instagram limits is:
- 1000 like/day 
- 500 comment/day 
- 500 follow and 500 defollow/day 

This is normal limits if you wont risk a ban...
