### ISSUE TITLE
Input areas disappearing. Instagram bot.

### ISSUE THREAD

**Issue by UN5T48L3** [social-manager-tools/social-manager-tools#55]
Replace the values below with your own:
### version
- **Social Manager Tools Version:** v0.6.2
- **Social Platform:** Instagram
- **Operating System:** Debian (Kali Linux 2018.2)

When I don't put any letter in the username area, it looks normal and shows all areas as expected.
But when I put anything in the username area,
some of inputs disappears.

### Screenshots
![ekran resmi 2018-12-23 17 11 28](https://user-images.githubusercontent.com/39417235/50384504-94c1af00-06d6-11e9-810d-a606f3b99b4b.png)
![ekran resmi 2018-12-23 17 11 37](https://user-images.githubusercontent.com/39417235/50384507-98edcc80-06d6-11e9-986d-232c75dfa1c0.png)

**Comment by UN5T48L3** [comment]
Same problem with OSX. Same version too.

**Comment by ptkdev** [comment]
What you expecteed?
Switch "social algorithm" select box for appear correct input.The various settings change according to the algorithm set, those that are not needed are hidden

**Comment by ptkdev** [comment]
If you want start two mode at the same time, example: 
1) select realistic_mode, compile form and press start. 
2) select comment_mode, compile form and press start

**Comment by UN5T48L3** [comment]
> If you want start two mode at the same time, example:
> 
> 1. select realistic_mode, compile form and press start.
> 2. select comment_mode, compile form and press start

Okay, I got it.
